config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products do
    member do
      patch :toggle_notify_expiration
    end

    collection do
      post :test_notification
    end
  end

  resource :job_schedule, only: %i[new create edit update show]
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :purchase_date, presence: true
  validates :expiration_date, presence: true
  validates :notify_expiration, inclusion: { in: [true, false] }

  def days_until_expiration
    (expiration_date - Time.zone.today).to_i
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name purchase_date expiration_date] # 検索を許可したい属性のみをこの配列に追加
  end

  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user

  def index
    @q = current_user.products.ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(15)
    @soon_expiring_count = @products.select { |p| (p.expiration_date - Time.zone.today).to_i < 7 }.count
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to @product, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: t('.success')
  end

  def toggle_notify_expiration
    product = Product.find(params[:id])
    product.update(notify_expiration: !product.notify_expiration)
    redirect_to products_path, notice: t('products.notifications.updated')
  end

  def test_notification
    # カレントユーザーのIDをパラメータとしてWorkerのperformメソッドをキューに追加します。
    ReminderMailerWorker.perform_async(current_user.id)

    redirect_to products_path, notice: t('products.notifications.sent')
  end

  private

  def set_product
    @product = Product.find_by(id: params[:id])
    return if @product

    flash[:alert] = t('products.errors.not_found')
    redirect_to root_path # または適切なパスへリダイレクト
  end

  def product_params
    params.require(:product).permit(:name, :purchase_date, :expiration_date, :notify_expiration)
  end

  def authorize_user
    return unless @product # これにより、@productがnilの場合にauthorize_userメソッドをスキップします。

    return if @product.user == current_user

    flash[:alert] = t('products.errors.unauthorized')
    redirect_to root_path # または適切なパスへリダイレクト
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, class: "space-y-4") do |form| %>
    <% if product.errors.any? %>
        <div id="error_explanation" class="p-4 mb-4 border border-red-400 text-red-700 bg-red-100 rounded">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul class="list-disc pl-5">
                <% product.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name, class: "block text-purple-700 text-sm font-bold mb-2" %>
        <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="field">
        <%= form.label :purchase_date, class: "block text-purple-700 text-sm font-bold mb-2" %>
        <%= form.date_field :purchase_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="field">
        <%= form.label :expiration_date, class: "block text-purple-700 text-sm font-bold mb-2" %>
        <%= form.date_field :expiration_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="field">
        <%= form.label :notify_expiration, '通知を受け取りますか？', class: "block text-purple-700 text-sm font-bold mb-2" %>
        <%= form.check_box :notify_expiration, { checked: product.notify_expiration || true, class: "rounded text-purple-600" } %>
    </div>

    <div class="actions">
        <%= form.submit class: "bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
<% end %>

app/views/products/edit.html.erb
<div class="max-w-md mx-auto p-6 bg-white rounded shadow-md mt-8">
    <h1 class="text-2xl font-bold text-purple-700 text-center">Edit Product</h1>

    <div class="mt-4 bg-white rounded-lg p-4">
        <%= render 'form', product: @product %>
    </div>

    <div class="mt-4 text-center">
        <%= link_to 'Show', @product, class: "text-purple-600 hover:text-purple-800 font-bold mr-4" %>
        <%= link_to 'Back', products_path, class: "text-purple-600 hover:text-purple-800 font-bold" %>
    </div>
</div>

app/views/products/index.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded shadow-md mt-8">
    <h1 class="text-2xl font-bold text-purple-700 text-center">在庫商品　一覧</h1>
    <h2 class="text-lg md:text-xl text-purple-600 text-center mt-4">消費期限7日以下の商品数 <%= @soon_expiring_count %> 個</h2>
<div class="flex justify-center space-x-4 mt-6">
<div class="flex space-x-4 justify-center my-6">
  <%= link_to 'スケジュール編集',
              edit_job_schedule_path,
              class: "bg-purple-600 text-white px-4 py-2 rounded-md shadow-md hover:bg-purple-700 transition-all duration-300" %>

  <%= link_to 'スケジュール表示',
              job_schedule_path,
              class: "bg-indigo-600 text-white px-4 py-2 rounded-md shadow-md hover:bg-indigo-700 transition-all duration-300" %>
</div>
</div>


    <div class="mt-4">
        <%= search_form_for @q, class: "flex flex-col md:flex-row gap-2 justify-center items-end" do |f| %>
            <%= f.label :name_cont, "商品名で検索:", class: "block text-purple-700" %>
            <%= f.search_field :name_cont, class: "form-input mt-1 block w-full rounded-md border-purple-300 shadow-sm" %>
            <%= f.submit "検索", class: "mt-2 md:mt-0 px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50" %>
        <% end %>
    </div>

    <%= button_to 'テスト通知', test_notification_products_path, method: :post, class: "mt-4 px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50" %>

    <table class="mt-4 w-full text-xs sm:text-sm text-left text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-purple-100">
            <tr>
                <th class="py-2 px-3">ユーザーメールアドレス</th>
                <th class="py-2 px-3">商品名</th>
                <th class="py-2 px-3">購入日</th>
                <th class="py-2 px-3">消費期限</th>
                <th class="py-2 px-3">残日数</th>
                <th class="py-2 px-3">通知</th>
                <th colspan="3" class="py-2 px-3"></th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
                <tr class="<%= 'bg-purple-100' if (product.expiration_date - Time.zone.today).to_i < 7 %>">
                    <td class="py-2 px-3"><%= product.user.email %></td>
                    <td class="py-2 px-3"><%= product.name %></td>
                    <td class="py-2 px-3"><%= product.purchase_date %></td>
                    <td class="py-2 px-3"><%= product.expiration_date %></td>
                    <td class="py-2 px-3"><%= product.days_until_expiration %>日</td>
                    <td class="py-2 px-3">
                        <%= button_to (product.notify_expiration ? 'On' : 'Off'), toggle_notify_expiration_product_path(product), method: :patch, class: "px-2 py-1 text-xs sm:text-sm bg-purple-600 text-white font-semibold rounded hover:bg-purple-700" %>
                    </td>
                    <td class="py-2 px-3"><%= link_to 'Show', product, class: "text-xs sm:text-sm text-blue-500 hover:text-blue-700" %></td>
                    <td class="py-2 px-3"><%= link_to 'Edit', edit_product_path(product), class: "text-xs sm:text-sm text-blue-500 hover:text-blue-700" %></td>
                    <td class="py-2 px-3"> <%= link_to 'Destroy', product, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "text-xs sm:text-sm text-red-500 hover:text-red-700" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= paginate @products, class: "mt-4 text-center" %>

    <div class="mt-4 text-center">
            <%= link_to 'New Product', new_product_path, class: "px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50" %>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="max-w-md mx-auto p-6 bg-white rounded shadow-md mt-8">
    <h1 class="text-2xl font-bold text-purple-700 text-center">New Product</h1>

    <div class="mt-4 bg-white shadow-md rounded-lg p-4">
        <%= render 'form', product: @product %>
    </div>

    <%= link_to 'Back', products_path, class: "mt-4 inline-block text-purple-600 hover:text-purple-800 font-bold" %>
</div>

app/views/products/show.html.erb
<div class="max-w-md mx-auto p-6 bg-white rounded shadow-md mt-8">
    <h1 class="text-2xl font-bold text-purple-700 text-center">Product Details</h1>

    <div class="mt-4">
        <p class="text-lg text-gray-700">
            <strong>Name:</strong>
            <%= @product.name %>
        </p>

        <p class="text-lg text-gray-700">
            <strong>Purchase Date:</strong>
            <%= @product.purchase_date %>
        </p>

        <p class="text-lg text-gray-700">
            <strong>Expiration Date:</strong>
            <%= @product.expiration_date %>
        </p>
    </div>

    <div class="text-center mt-4">
        <%= link_to 'Edit', edit_product_path(@product), class: "mr-2 px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50" %>
        <%= link_to 'Back', products_path, class: "px-4 py-2 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50" %>
    </div>
</div>